# Time stamp
Header header

# Latitude [degrees]. Positive is north of equator; negative is south.
float32 latitude

# Longitude [degrees]. Positive is east of prime meridian; negative is west.
float32 longitude

# Altitude [m]. Positive is above the WGS 84 ellipsoid
# (quiet NaN if no altitude is available).
float32 altitude

# utm data format.
float32 utm_easting
float32 utm_northing
int16 Zone
string fields
